live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#767676"
blue = "#3b78ff"
cyan = "#61d6d6"
green = "#16c60c"
magenta = "#b4009e"
red = "#e74856"
white = "#f0f0ff"
yellow = "#f9f1a5"

[colors.cursor]
cursor = "#f3c504"
text = "CellBackground"

[colors.normal]
black = "#0c0c0c"
blue = "#82aaff"
cyan = "#3a96dd"
green = "#13a10e"
magenta = "#881798"
red = "#c50f1f"
white = "#ccccd0"
yellow = "#c19c00"

[colors.primary]
background = "#000000"
foreground = "#c6cae0"

[colors.selection]
background = "#86868c"
text = "#000000"

[cursor]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "BitstreamVeraSansMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BitstreamVeraSansMono Nerd Font"
style = "Bold Oblique"

[font.italic]
family = "BitstreamVeraSansMono Nerd Font"
style = "Oblique"

[font.normal]
family = "BitstreamVeraSansMono Nerd Font"
style = "Roman"

[font.offset]
x = 0
y = 1

[scrolling]
history = 4000

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
title = "Terminal"

[window.class]
general = "Terminal"
instance = "Terminal"

[window.dimensions]
columns = 100
lines = 32

[window.padding]
x = 4
y = 4
